services:
  - type: web
    name: constitutional-ai-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11