# .streamlit/config.toml

[theme]
# The primary color for interactive elements
primaryColor = "#FF4B4B"  # A bright coral red

# The background color for the main content area
backgroundColor = "#FFFFFF" # White

# The background color for the sidebar and other secondary areas
secondaryBackgroundColor = "#F0F2F6" # A light grey

# The color of the text
textColor = "#31333F"

# The font family for the app
# Can be "sans serif", "serif", or "monospace"
font = "sans serif"