# .streamlit/config.toml

[theme]
# A professional blue for interactive elements
primaryColor="#0068C9"

# A very light grey for the main background
backgroundColor="#F0F2F6"

# A clean white for the sidebar and other elements
secondaryBackgroundColor="#FFFFFF"

# Dark text for high contrast and readability
textColor="#0D1117"

# Standard font
font="sans serif"